# Generated by Django 5.2.5 on 2025-09-09 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('postal_code', models.CharField(max_length=10, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('xp_total', models.IntegerField(default=0)),
            ],
        ),
    ]
