# Generated by Django 5.2.5 on 2025-09-09 07:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255, null=True)),
                ('birthdate', models.DateField(null=True)),
            ],
        ),
    ]
