# Generated by Django 5.2.5 on 2025-09-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_collection_alter_author_name_alter_publisher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('language', models.CharField(max_length=2)),
                ('publication_date', models.DateField()),
                ('cover_url', models.TextField(null=True)),
                ('pages', models.IntegerField()),
                ('authors', models.ManyToManyField(related_name='books', to='books.author')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.collection')),
                ('genres', models.ManyToManyField(related_name='books', to='books.genre')),
                ('publishers', models.ManyToManyField(related_name='books', to='books.publisher')),
                ('themes', models.ManyToManyField(related_name='books', to='books.theme')),
            ],
        ),
    ]
