# Generated by Django 5.2.5 on 2025-09-10 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('reserved', 'Reserved'), ('lost', 'Lost')], default='available', max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('book', models.ForeignKey(db_column='book_isbn', on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='books.book')),
            ],
        ),
    ]
