# Generated by Django 5.2.5 on 2025-09-03 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='last_password_change',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 21, 54, 53, 640851, tzinfo=datetime.timezone.utc)),
        ),
    ]
