# Generated by Django 5.2.5 on 2025-09-04 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_auth_last_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='last_password_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
